CONTINUOUS_FEATURE_COLUMNS = ['TotRmsAbvGrd', 'WoodDeckSF', 'YrSold', '1stFlrSF']
CATEGORICAL_FEATURE_COLUMNS = ['Foundation', 'KitchenQual']
FEATURE_COLUMNS = CONTINUOUS_FEATURE_COLUMNS + CATEGORICAL_FEATURE_COLUMNS
LABEL_COLUMN = 'SalePrice'

SERIALIZER_EXTENSION = '.joblib'
ARTIFACTS_DIR = '../../models/house-prices'
SCALER_PATH = f'{ARTIFACTS_DIR}/scaler{SERIALIZER_EXTENSION}'
ONE_HOT_ENCODER_PATH = f'{ARTIFACTS_DIR}/one_hot_encoder{SERIALIZER_EXTENSION}'
MODEL_PATH = f'{ARTIFACTS_DIR}/model{SERIALIZER_EXTENSION}'
