{
 "title": "House Prices Dashboard",
 "time": { "from": "2015-01-01T00:00:00.000Z", "to": "2028-12-14T00:00:00.000Z" },
 "panels": [
  {
   "title": "Price by Year Sold",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT yrsold, AVG(saleprice) FROM new_predictions GROUP BY yrsold LIMIT 50"
    }
   ]
  },
  {
   "title": "Sale Price by Foundation Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT foundation, AVG(saleprice) FROM new_predictions GROUP BY foundation LIMIT 50"
    }
   ]
  },
  {
   "title": "Total Rows in DB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM new_predictions LIMIT 50"
    }
   ]
  },
  {
   "title": "Sale Price by Kitchen Quality",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT AVG(saleprice), kitchenqual FROM new_predictions GROUP BY kitchenqual LIMIT 50"
    }
   ]
  },
  {
   "title": "Avg Sale Price by Year of Construction",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT yrsold, AVG(saleprice) FROM new_predictions GROUP BY yrsold LIMIT 50"
    }
   ]
  },
  {
   "title": "Average Sale Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(saleprice) FROM new_predictions LIMIT 50"
    }
   ]
  },
  {
   "title": "First Floor Ft^2 Correlation",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT firstflrsf, saleprice FROM new_predictions LIMIT 50"
    }
   ]
  },
  {
   "title": "Wood Deck Ft^2 Correlation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT wooddecksf, saleprice FROM new_predictions LIMIT 50"
    }
   ]
  }
 ]
}